version: '3.7'
services:
  # container listens on 8000
  kafka-connect-ui:
    image: ${IMAGE_FQDN}
    ports:
      - "${BCM_SERVICE_PORT}:8000"
    networks:
      - kafkaconnectnet
    environment:
      CONNECT_URL: http://kafkaconnect:8083
      PROXY: "true"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - engine.labels.bcm-underlay == true

networks:
  kafkaconnectnet:
    external: true
    name: kafkaconnect_kafkaconnectnet