version: '3.7'
services:
  # container listens on 8000
  schema-registry-ui:
    image: ${IMAGE_FQDN}
    ports:
      - "${BCM_SERVICE_PORT}:8000"
    networks:
      - schemaregistrynet
    environment:
      SCHEMAREGISTRY_URL: http://schemaregistry:8081
      PROXY: "true"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - engine.labels.bcm-underlay == true

networks:
  schemaregistrynet:
    external: true
    name: kafkaschemareg_schemaregistrynet