#cloud-config

# Add users to the system. Users are added after groups are added.
users:
  - name: bcm
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: lxd
    ssh_authorized_keys:
      - $SSH_AUTHORIZED_KEY
