version: '3.7'
services:
  lnd:
    image: ${IMAGE_NAME}
    hostname: lnd-${BCM_ACTIVE_CHAIN:-}
    volumes:
      - data:/root/.lnd
      - admin-macaroon:/root/.lnd_admin_macaroon
      - readonly-macaroon:/root/.lnd_readonly_macaroon
      - log-data:/var/logs/lnd
      - bitcoin-data:/root/.bitcoin:ro
      - bitcoin-cli:/usr/local/bin:ro
      - tor-data:/root/.tor:ro
    environment:
      LND_CERTIFICATE_HOSTNAME: lnd-${BCM_ACTIVE_CHAIN:-}  #this is so there are no certificate verification issues on lncli-web
      BCM_ACTIVE_CHAIN: ${BCM_ACTIVE_CHAIN:-}
      TOR_SOCKS5_PROXY_HOSTNAME: ${TOR_SOCKS5_PROXY_HOSTNAME}
      BITCOIND_ZMQ_BLOCK_PORT: ${BITCOIND_ZMQ_BLOCK_PORT}
      BITCOIND_ZMQ_TX_PORT: ${BITCOIND_ZMQ_TX_PORT}
      CHAIN_TEXT: ${CHAIN_TEXT}
    networks:
      torsocksnet:
      #toronionnet:
      bitcoindrpcnet:
      lndrpcnet:
        aliases:
          - lndrpc-${BCM_ACTIVE_CHAIN}
    secrets:
      - source: lnd-config
        target: /secrets/lnd.conf
        uid: '0'
        gid: '0'
        mode: 0444
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - engine.labels.bcm-bitcoin${BCM_ACTIVE_CHAIN:-} == true


networks:
  torsocksnet:
    external: true
    name: torproxy-${BCM_ACTIVE_CHAIN:-}_torsocksnet

  # toronionnet:
  #   external: true
  #   name: toronion_lndnet-${BCM_ACTIVE_CHAIN:-}

  lndrpcnet:
    driver: overlay
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.240.0/24

  bitcoindrpcnet:
    external: true
    name: bitcoind-${BCM_ACTIVE_CHAIN:-}_bitcoindrpcnet

secrets:
  lnd-config:
    file: lnd.conf

volumes:
  data:
  log-data:
  
  admin-macaroon:
  readonly-macaroon:

  tor-data:
    external: true
    name: torproxy-${BCM_ACTIVE_CHAIN:-}_data

  bitcoin-data:
    external: true
    name: bitcoind-${BCM_ACTIVE_CHAIN:-}_data

  bitcoin-cli:
    external: true
    name: bitcoind-${BCM_ACTIVE_CHAIN:-}_cli

  bitcoin-cookie:
    external: true
    name: bitcoind-${BCM_ACTIVE_CHAIN:-}_cookie
  
  bitcoin-rpc:
    external: true
    name: bitcoind-${BCM_ACTIVE_CHAIN:-}_rpc-lnd
