version: '3.7'
services:
  toronion:
    image: ${DOCKER_IMAGE}
    volumes:
      - data:/root/.tor
      - logs:/var/log/tor
    networks:
      bitcoindnet-mainnet:
      bitcoindnet-testnet:
      bitcoindnet-regtest:
    configs:
      - source: torrc-config
        target: /etc/tor/torrc
        mode: 0640
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - engine.labels.bcm-underlay == true

networks:
  bitcoindnet-mainnet:
    driver: overlay
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.100.0/27

  bitcoindnet-testnet:
    driver: overlay
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.100.32/27

  bitcoindnet-regtest:
    driver: overlay
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.100.64/27

volumes:
  data:
  logs:

configs:
  torrc-config:
    file: torrc
