version: '3.7'
services:
  toronion:
    image: ${DOCKER_IMAGE}
    volumes:
      - data:/root/.tor
      - logs:/var/log/tor
    networks: 
      bitcoindnet:
    configs:
      - source: torrc-config
        target: /etc/tor/torrc
        mode: 0640
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - engine.labels.bcm-underlay == true

networks:
  bitcoindnet:
    driver: overlay
    attachable: true
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.200.0/24

  # toronion-lnd-rpc:
  #   driver: overlay
  #   attachable: true
  #   ipam:
  #     driver: default
  #     config:
  #       - subnet: "172.16.200.4/30"

  # toronion-ridethelightning-http:
  #   driver: overlay
  #   attachable: true
  #   ipam:
  #     driver: default
  #     config:
  #       - subnet: "172.16.200.8/30"

  # toronion-electrs-rpc:
  #   driver: overlay
  #   attachable: true
  #   ipam:
  #     driver: default
  #     config:
  #       - subnet: "172.16.200.12/30"

volumes:
  data:
  logs:

configs:
  torrc-config:
    file: torrc
