#!/bin/bash


export BCM_GW_TEMPLATE_NAME="bcm-gw-template"
export BCM_GATEWAY_CONTAINER_TEMPLATE_DELETE=1
export BCM_LXC_GATEWAY_CONTAINER_NAME="bcm-gateway"


export BCM_GATEWAY_PROFILE_GATEWAYPROFILE_CREATE=1
export BCM_GATEWAY_CONTAINER_DELETE=1


export BCM_GATEWAY_PROFILE_GATEWAYPROFILE_DELETE=1
export BCM_GATEWAY_STORAGE_DOCKERVOL_DELETE=1
export BCM_LXC_GATEWAY_STORAGE_DOCKERVOL_NAME="bcm-gateway-dockervol"
export BCM_REMOVE_TEMPLATE_FLAG=1