version: '3.7'
services:

  #listens on 9021
  control-center:
    image: ${IMAGE_FQDN}
    ports:
      - "${BCM_SERVICE_PORT}:9021"
    networks:
      - kafkanet
      - zookeepernet
      - kafkaconnectnet
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: ${KAFKA_CONNECT:-broker-01:9092}
      CONTROL_CENTER_ZOOKEEPER_CONNECT: ${ZOOKEEPER_CONNECT:-zookeeper-01:2181}
      #CONTROL_CENTER_CONNECT_CLUSTER: http://kafka-connect:8083
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - engine.labels.bcm-underlay == true

networks:
  kafkanet:
    external: true
    name: kafkanet

  zookeepernet:
    external: true
    name: zookeepernet

  kafkaconnectnet:
    external: true
    name: kafkaconnect_kafkaconnectnet