version: '3.7'
services:
  portainer:
    image: ${IMAGE_FQDN}
    ports:
      - "${BCM_SERVICE_PORT}:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - engine.labels.bcm-manager == true
