#!/bin/bash

export BCM_HOSTTEMPLATE_IMAGE_BCM_TEMPLATE_DELETE=1
export BCM_HOSTTEMPLATE_IMAGE_BCM_BIONIC_BASE_DELETE=0
export BCM_ADMIN_IMAGE_BCMTEMPLATE_MAKE_PUBLIC=1
export BCM_GATEWAY_STORAGE_DOCKERVOL_CREATE=1

export BCM_CLUSTERS_DIR="$BCM_RUNTIME_DIR/clusters"


