#!/bin/bash

set -Eeuo pipefail
cd "$(dirname "$0")"

if [[ -z $BCM_ACTIVE ]]; then
    BCM_ACTIVE=1
fi

if ! snap list | grep -q lxd; then
    bash -c "$BCM_GIT_DIR/cli/commands/install/snap_install_lxd_local.sh"
fi

# shellcheck disable=1090
source ./env

if ! snap list | grep -q docker; then
    if ! docker image list --format "{{.Repository}},{{.Tag}}" | grep -q "bcm-trezor,$BCM_VERSION"; then
        bash -c "$BCM_GIT_DIR/controller/build.sh"
    fi
else
    bash -c "$BCM_GIT_DIR/cli/commands/install/snap_install_docker.sh"
fi

# call the CLI entrypoint.
./commands/cli_entrypoint.sh "$@"
