#!/bin/bash

set -e
cd "$(dirname "$0")"

# make the following environment variables available to child shells
export BCM_CERTS_DIR=$BCM_RUNTIME_DIR/certs
export BCM_PROJECTS_DIR=$BCM_RUNTIME_DIR/projects
export BCM_CLUSTERS_DIR=$BCM_RUNTIME_DIR/clusters
export BCM_PASSWORDS_DIR=$BCM_RUNTIME_DIR/passwords
export BCM_DEPLOYMENTS_DIR=$BCM_RUNTIME_DIR/deployments

if [[ -z $BCM_DEBUG ]]; then
    export BCM_DEBUG=0
fi

if [[ $BCM_DEBUG = 1 ]]; then
    export BCM_DEBUG=$BCM_DEBUG
    echo "BCM_CERTS_DIR: $BCM_CERTS_DIR"
    echo "BCM_PROJECTS_DIR: $BCM_PROJECTS_DIR"
    echo "BCM_CLUSTERS_DIR: $BCM_CLUSTERS_DIR"
    echo "BCM_PASSWORDS_DIR: $BCM_PASSWORDS_DIR"
fi

./commands/cli_entrypoint.sh "$@"
