#!/bin/bash

# if the user does not specify this, it will be generated automatically and stored at $BCM_RUNTIME_DIR/$(lxc remote get-default).env

export BCM_ADMIN_RSYNC_INSTALL="true"
export BCM_DEFAULT_NGINX_DOCKER_IMAGE="nginx:1.15.2-perl"
export BCM_HOSTTEMPLATE_PROFILE_DOCKER_PRIVILEGED_DELETE="true"
export BCM_HOSTTEMPLATE_PROFILE_DOCKER_UNPRIVILEGED_CREATE="true"
export BCM_HOSTTEMPLATE_PROFILE_DOCKER_UNPRIVILEGED_DELETE="true"

export BCM_STORAGE_bcm_btrfs_CREATE="true"
export BCM_STORAGE_bcm_btrfs_DELETE="true"
export BCM_LXD_OPS="$BCM_LOCAL_GIT_REPO_DIR/lxd/shared"
export BCM_LXD_HOST_PROFILES="$BCM_LOCAL_GIT_REPO_DIR/lxd/host_template/lxd_profiles"
export BCM_CLUSTER_DIR=$BCM_RUNTIME_DIR/clusters/$BCM_CLUSTER_NAME

#####################
####################
#####################3
export BCM_LXC_BCMNETTEMPLATE_STORAGE_DOCKERVOL_NAME="bcmnet-template-dockervol"
export BCM_LXC_BCMNETTEMPLATE_CONTAINER_TEMPLATE_NAME="bcmnet-template"
export BCM_LXC_BCMNETTEMPLATE_CONTAINER_NAME="bcmnet-template"

export BCM_ADMIN_BCMNETTEMPLATE_CREATE="true"


export BCM_BCMNETTEMPLATE_CONTAINER_CREATE="true"
export BCM_BCMNETTEMPLATE_CONTAINER_DELETE="true"

export BCM_BCMNETTEMPLATE_PROFILE_CACHESTACK_PROFILE_CREATE="true"
export BCM_BCMNETTEMPLATE_PROFILE_CACHESTACK_STANDALONE_PROFILE_DELETE="true"

export BCM_BCMNETTEMPLATE_NETWORK_LXDBR0CACHESTACK_CREATE="true"
export BCM_BCMNETTEMPLATE_NETWORK_LXDBR0CACHESTACK_DELETE="true"

export BCM_BCMNETTEMPLATE_STORAGE_DOCKERVOL_CREATE="true"
export BCM_BCMNETTEMPLATE_STORAGE_DOCKERVOL_DELETE="true"
export BCM_BCMNETTEMPLATE_STORAGE_DOCKERVOL_NAME="bcmnet-template-dockervol"


# `cachestack` installation options.
export BCM_BCMNETTEMPLATE_BITCOIND_TESTNET_INSTALL="false"
export BCM_BCMNETTEMPLATE_BITCOIND_TESTNET_RSYNC_SEED="false"
export BCM_BCMNETTEMPLATE_BITCOIND_TESTNET_RSYNC_SEED_SOURCEDIR=""
export BCM_BCMNETTEMPLATE_BITCOIND_MAINNET_INSTALL="false"
export BCM_BCMNETTEMPLATE_IPFSCACHE_INSTALL="false"
export BCM_BCMNETTEMPLATE_PRIVATEREGISTRY_INSTALL="false"
export BCM_BCMNETTEMPLATE_REGISTRYMIRRORS_INSTALL="false"
export BCM_BCMNETTEMPLATE_SQUID_INSTALL="false"
export BCM_BCMNETTEMPLATE_TOR_SOCKS5_PROXY_INSTALL="false"
export BCM_BCMNETTEMPLATE_RSYNCD_INSTALL="false"
export BCM_BCMNETTEMPLATE_RSYNCD_BUILD="true"
export BCM_BCMNETTEMPLATE_RSYNCD_BUILD_IMAGE="cachestack.lan/rsyncd:latest"


export BCM_BCMNETINST_RSYNC_BUILDER_NAME="bcm-rsync-builder"




# if yes, then the 'gateway' LXD host will be created
export BCM_ADMIN_GATEWAY_INSTALL="true"
export BCM_GATEWAY_DELETE="false"

export BCM_GATEWAY_CONTAINER_CREATE="true"

export BCM_GATEWAY_CONTAINER_TEMPLATE_CREATE="true"
export BCM_GATEWAY_PROFILE_GATEWAYPROFILE_CREATE="true"
export BCM_GATEWAY_NETWORKS_CREATE="true"


export BCM_GATEWAY_CONTAINER_DELETE="true"
export BCM_GATEWAY_STORAGE_DOCKERVOL_DELETE="true"
export BCM_GATEWAY_CONTAINER_TEMPLATE_DELETE="true"
export BCM_GATEWAY_PROFILE_GATEWAYPROFILE_DELETE="true"
export BCM_GATEWAY_NETWORKS_DELETE="true"







# needed during scripts, do not remove
export BCM_GW_TEMPLATE_NAME="bcm-template-gateway"
export BCM_LXC_GATEWAY_CONTAINER_NAME="bcm-gateway"

