#!/bin/bash

export BCM_BCMNETTEMPLATE_SQUID_INSTALL="false"
export BCM_BCMNETTEMPLATE_TOR_SOCKS5_PROXY_INSTALL="false"
export BCM_BCMNETTEMPLATE_RSYNCD_INSTALL="false"
export BCM_BCMNETINST_RSYNC_BUILDER_NAME="bcm-rsync-builder"