version: '3.7'
services:
  torproxy:
    image: ${DOCKER_IMAGE}
    volumes:
      - data:/root/.tor
    networks: 
      torsocksnet:
        aliases:
          - torsocks
    configs:
      - source: torrc-config
        target: /etc/tor/torrc
        mode: 0640
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - engine.labels.bcm-bitcoin${BCM_ACTIVE_CHAIN:-} == true

# we attach the tor daemon to the host networking stack
# so the ports will be exposed ONLY on the manager host
# instead of an overlay network spanning all LXC hosts.
networks:
  torsocksnet:
    driver: overlay
    attachable: true

volumes:
  data:

configs:
  torrc-config:
    file: torrc
