#!/bin/bash

echo "GNUPGHOME: $GNUPGHOME"
echo "PASSWORD_STORE_DIR: $PASSWORD_STORE_DIR"
echo "SSH_DIR: $SSH_DIR"
echo "BCM_ACTIVE: $BCM_ACTIVE"
echo "BCM_CLUSTER_NAME:  $BCM_CLUSTER_NAME"
echo "BCM_PROJECT_NAME: $BCM_PROJECT_NAME"
echo "BCM_CERT_NAME: $BCM_CERT_NAME"
echo "BCM_CERT_USERNAME: $BCM_CERT_USERNAME"
echo "BCM_CERT_HOSTNAME: $BCM_CERT_HOSTNAME"
echo "BCM_DEBUG: $BCM_DEBUG"
echo "BCM_PROJECT_USERNAME: $BCM_PROJECT_USERNAME"
echo ""
