version: '3.7'
services:
  private-registry:
    image: ${DOCKER_IMAGE}
    ports: 
      - "${TARGET_PORT}:5000"
    volumes:
      - private-registry-data:/data
    environment:
      REGISTRY_HTTP_ADDR: :5000
      REGISTRY_HTTP_HOST: http://${TARGET_HOST}:${TARGET_PORT}
      REGISTRY_HTTP_SECRET: ${REGISTRY_HTTP_SECRET:-CHANGEME}
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${TARGET_HOST}


volumes:
  private-registry-data:

