version: '3.7'
services:
  registry-mirror:
    image: ${DOCKER_IMAGE}
    ports:
      - "${TARGET_PORT}:5000"
    volumes:
      - registrymirrorimage-data:/data
    environment:
      REGISTRY_HTTP_ADDR: :5000
      REGISTRY_HTTP_HOST: http://${TARGET_HOST}:5000
      REGISTRY_HTTP_SECRET: ${REGISTRY_HTTP_SECRET:-CHANGEME}
      REGISTRY_PROXY_REMOTEURL: ${REGISTRY_PROXY_REMOTEURL:-https://registry-1.docker.io}
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${TARGET_HOST}
    # secrets:
    #   - source: regmirror_tls_cert
    #     target: /var/lib/registry/regmirror:5000.cert
    #     uid: '0'
    #     gid: '0'
    #     mode: 0400
    #   - source: regmirror_tls_key
    #     target: /var/lib/registry/regmirror:5000.key
    #     uid: '0'
    #     gid: '0'
    #     mode: 0400
    #   - source: regmirror_ca_crt
    #     target: /var/lib/registry/ca.crt
    #     uid: '0'
    #     gid: '0'
    #     mode: 0400


# secrets:
#   regmirror_tls_cert:
#     file: regmirror.cert
#   regmirror_tls_key:
#     file: regmirror.key
#   regmirror_ca_crt:
#     file: ca.crt

volumes:
  registrymirrorimage-data: