version: '3.7'
services:
  bitcoind:
    image: ${DOCKER_IMAGE}
    hostname: bitcoind-${BCM_ACTIVE_CHAIN}
    volumes:
      - wallet:/bitcoin/wallet
      - data:/root/.bitcoin
      - blocks:/root/.blocks
      - cli:/usr/local/bin
      - tor-data:/root/.tor:ro
    environment:
      BCM_ACTIVE_CHAIN: ${BCM_ACTIVE_CHAIN:-}
      BITCOIND_RPC_PORT: ${BITCOIND_RPC_PORT:-}
      INITIAL_BLOCK_DOWNLOAD: ${INITIAL_BLOCK_DOWNLOAD:-1}
      BITCOIND_ZMQ_BLOCK_PORT: ${BITCOIND_ZMQ_BLOCK_PORT:-}
      BITCOIND_ZMQ_TX_PORT: ${BITCOIND_ZMQ_TX_PORT:-}
    networks:
      bitcoindrpcnet:
        aliases:
          - bitcoindrpc-${BCM_ACTIVE_CHAIN}
        ipv4_address: ${BITCOIND_RPCNET_IP:-}
      torsocksnet:
      toronionnet:
        ipv4_address: ${BITCOIND_ONIONNET_IP:-}
    configs:
      - source: bitcoin-config
        target: /config/bitcoin.conf
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - engine.labels.bcm-bitcoin${BCM_ACTIVE_CHAIN:-} == true

configs:
  bitcoin-config:
    file: bitcoin.conf

volumes:
  wallet:
  blocks:
  cli:
  
  data:
    external: true
    name: bitcoind-${BCM_ACTIVE_CHAIN:-}_data

  tor-data:
    external: true
    name: torproxy-${BCM_ACTIVE_CHAIN:-}_data

networks:
  bitcoindrpcnet:
    driver: overlay
    attachable: true
    internal: true
    ipam:
      driver: default
      config:
        - subnet: ${BITCOIND_RPCNET_SUBNET:-}

  torsocksnet:
    external: true
    name: torproxy-${BCM_ACTIVE_CHAIN:-}_torsocksnet

  toronionnet:
    external: true
    name: toronion-${BCM_ACTIVE_CHAIN:-}_bitcoindnet