version: '3.7'
services:
  bitcoind:
    image: ${DOCKER_IMAGE}
    hostname: bitcoind-${BCM_ACTIVE_CHAIN}
    volumes:
      - wallet:/bitcoin/wallet
      - data:/root/.bitcoin
      - blocks:/root/.blocks
      - cli:/usr/local/bin
      - tor-data:/root/.tor:ro
    environment:
      BCM_ACTIVE_CHAIN: ${BCM_ACTIVE_CHAIN:-}
      BITCOIND_RPC_PORT: ${BITCOIND_RPC_PORT:-}
      INITIAL_BLOCK_DOWNLOAD: ${INITIAL_BLOCK_DOWNLOAD:-1}
    networks:
      bitcoindrpcnet:
        aliases:
          - bitcoindrpc-${BCM_ACTIVE_CHAIN}
        ipv4_address: 172.16.238.3/24
      torsocksnet:
      toronionnet:
        ipv4_address: 172.16.200.6/24
    configs:
      - source: bitcoin-config
        target: /config/bitcoin.conf
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - engine.labels.bcm-bitcoin == true

configs:
  bitcoin-config:
    file: bitcoin.conf

volumes:
  wallet:
  blocks:
  cli:
  
  data:
    external: true
    name: bitcoind-${BCM_ACTIVE_CHAIN:-}_data

  tor-data:
    external: true
    name: torproxy-${BCM_ACTIVE_CHAIN:-}_data

networks:
  bitcoindrpcnet:
    driver: overlay
    attachable: true
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24

  torsocksnet:
    external: true
    name: torproxy-${BCM_ACTIVE_CHAIN:-}_torsocksnet

  toronionnet:
    external: true
    name: toronion-${BCM_ACTIVE_CHAIN:-}_bitcoindnet