version: '3.4'
services:
  registry-mirror:
    image: registry:2.6.2
    ports: 
      - "5000:5000"
    networks:
      - registrynet
    volumes:
      - registry-data:/data
    environment:
      REGISTRY_PROXY_REMOTEURL: ${REGISTRY_PROXY_REMOTEURL:-http://registry-1.docker.io}
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
    deploy:
      mode: replicated
      replicas: 1

  elastic-mirror:
    image: registry:2.6.2
    ports: 
      - "5020:5020"
    networks:
      - registrynet
    volumes:
      - elastic-data:/data
    environment:
      REGISTRY_PROXY_REMOTEURL: ${ELASTIC_REGISTRY_PROXY_REMOTEURL:-https://docker.elastic.co}
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
      REGISTRY_HTTP_ADDR: 0.0.0.0:5020
    deploy:
      mode: replicated
      replicas: 1

volumes:
  registry-data:
    driver: local
  elastic-data:
    driver: local
    
networks:
  registrynet: